### PR TITLE
feat: add deprecation notice

### PR DESCRIPTION
**Pull request by madpah**
And direct users to the new Sonatype Platform Browser Extension

### CODE REVIEW

**Comment by madpah** [comment]
Screenshot 2023-07-11 at 08 54 56
Screenshot 2023-07-11 at 08 59 05

**Review by maurycupitt — COMMENTED** [review]
Maybe reference for those using OSS Index as the data source, they should continue to use the old version until the new version supports OSS Index.  This is making the assumption that people are using it with OSS Index.

**Comment by madpah** [comment]
Update @maurycupitt - let me know your thoughts now.

**Pull request merged**
